# OpenCommunity Chatty

#
# Death message
#

death-prefix: "&#c6e2ff☠ "

#
# Chat correction
#

# With an upper letter
chat-correction: true

# Anti caps
anti-caps: true
# In percents
anti-caps-amount: 20
# Check only when message longer than
anti-caps-min: 10

#
# Chat format
#

# Chat message formats for different player groups
chat-formats:
  # Default format for all players
  default: "&#c6e2ff&l%player% >&f "
  # Format for players with the "opencommunity.moder" permission
  moder: "&#ffc6e2&l%player% >&f "
  moder-hover: "&#ffc6e2&l✔ Original Community Moderator"

#
# Local chat
#

# The prefix for the local chat messages
local-chat-prefix: "&#9fff9f&o%chatname% &f&#9fff9f&l%player% >&f "

#
# Announcements
#

# Announcement interval in minutes
announcement-interval: 5

# Announcement prefix
announcement-prefix: '[Announcement] '

# Announcement messages
announcement-messages:
  - 'Welcome to our server! Enjoy your time here.'
  - 'Don''t forget to check out our website for more information.'
  - 'Join our Discord for the latest updates and to connect with other players.'

#
# Join / Leave Messages
#

# Join message prefix
join-prefix: '&2✔ &#c6e2ff&l'

# Leave message prefix
leave-prefix: '&4✘ &#c6e2ff&l'

# Join messages
join-messages:
  - '%player% has joined the server!'
  - 'Welcome to the server, %player%!'
  - 'Glad to have you, %player%!'

# Leave messages
leave-messages:
  - '%player% has left the server.'
  - 'Goodbye %player%, see you soon!'
  - '%player% will be missed.'

# error messages
error-messages:
  not-a-player: "This command can only be used by players."